server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"

clientId: "local version of client id"
secret: "local version of  secret"
location: "local version of location"
---
spring:
  profiles: cloud

clientId: ${vcap.services.my-credhub-instance.credentials.clientId}
secret: ${vcap.services.my-credhub-instance.credentials.secret}
