server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: cloud

clientId: ${vcap.services.my-credhub-instance.credentials.clientId}
secret: ${vcap.services.my-credhub-instance.credentials.secret}
